### ISSUE TITLE
Issue on using moment type

### ISSUE THREAD

**Issue by truongnmt** [Bialogs/bootstrap4-datetime-picker-rails#3]
On creating option for `min/maxDate`
```js
Default: false
Accepts: date, moment, string
```

This is my code:
```js
const DATE_PICKER_OPTIONS = {
    useCurrent: true,
    format: 'Do MMM',
    minDate: moment()
};

function initDatePicker() {
    $('.datetimepicker-input').datetimepicker(DATE_PICKER_OPTIONS);
}
```

But I have a weird effect is that when click in the input, the date picker not open.
Only after I click again, the date picker show up.
Same problem when I'm using `moment([])` or  `moment({});`

**Comment by Bialogs** [comment]
You should probably ask this question over at https://github.com/tempusdominus/bootstrap-4
