### ISSUE TITLE
Is this localizable (de / german?)

### ISSUE THREAD

**Issue by tclaus** [Bialogs/bootstrap4-datetime-picker-rails#5]
You forked from nerian - this repo is localizable (but throws a bunch of depreciated errors) 
- is this datepicker also localizable?

**Comment by Bialogs** [comment]
Yes, but let me clarify something.

This gem only exposes the Tempus Dominus javascript and stylesheets. Any localization support is just configuration of those assets.

According to the [FAQ](https://tempusdominus.github.io/bootstrap-4/FAQ/) you can specify locale options during configuration of the picker. To do that you'll need to use the `momentjs` locales. Instructions for using a specific locale with `momentjs` are found [here](https://github.com/derekprior/momentjs-rails). Available momentjs locales are found are found [here](https://github.com/moment/moment/tree/master/locale).

**Comment by Bialogs** [comment]
I have added a bit more information regarding this to this project's README.md
