### ISSUE TITLE
Not working with Rails 5.2.1

### ISSUE THREAD

**Issue by scmdcs** [Bialogs/bootstrap4-datetime-picker-rails#6]
I installed everything as you described, but I can't get it to work with rails 5.2, when I click on the input field nothing happens. 
application.scss
`@import "bootstrap";
@import "tempusdominus-bootstrap-4";`
application.js
`//= require rails-ujs
//= require activestorage
//= require jquery3
//= require turbolinks
//= require popper
//= require tempusdominus-bootstrap-4.js
//= require moment
//= require bootstrap
//= require_tree .`
simple html

 `<in put class="datepicker" type="text" >` I mispelled input otherwise github would render it as html

and coffee script
`$(document).on "turbolinks:load", -> \n
  console.log("prova") \n
  $('.datepicker').datetimepicker();` I also added the newline simply for an easier understanding
If i try the gem 'bootstrap-datepicker-rails' works perfectly but this one(I need also the time) is not working

**Comment by Bialogs** [comment]
You're missing some critical HTML attributes to get the datepicker to work correctly. Please review usage instructions/docs: https://tempusdominus.github.io/bootstrap-4/Usage/

Also note that this project is just a fork of the `bootstrap-datepicker-rails` to get the gem structure. It doesn't share any of the asset code. What you've done previously with `bootstrap-datepicker-rails` is not likely to work/behave the same as the Tempus Dominus assets.
