### ISSUE TITLE
Add mementjs dependency

### ISSUE THREAD

**Issue by wayne5540** [Bialogs/bootstrap4-datetime-picker-rails#7]
I got error by adding following to `application.js`

```
//= require moment
//= require tempusdominus-bootstrap-4.js
```

Error: `couldn't find file 'moment' with type 'application/javascript'`

I got this error because I don't have momentjs installed. Fixed once I install momentjs myself.

I think it's good to add a cached momentjs file into this gem or add [momentjs-rails](https://github.com/derekprior/momentjs-rails) dependency. I personal prefer adding a cached version.

Or at least we can add some instruction into README to remind users to install momentjs themselves.

How do you think?

**Comment by Bialogs** [comment]
`momentjs-rails` is already a dependency of this gem. See gemspec: https://github.com/Bialogs/bootstrap4-datetime-picker-rails/blob/master/bootstrap4_datetime_picker_rails.gemspec#L16

**Comment by wayne5540** [comment]
Cool, didn't notice that since I'm using `v1.7.1`. Close this issue then. Thanks.

For others who had same error, just add `gem 'momentjs-rails'` into your `Gemfile` will be fine.
